name: spark
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]

permissions:
  contents: write  # Permite que GitHub Actions haga push al repositorio

jobs:
  spark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Revisa el código
      - run: |
          python -m pip install --upgrade pip
          pip install -r streamlit/requirements.txt # Instala dependencias
      - run: |
          python streamlit/procesamiento_spark.py # Ejecuta el script de Spark
      - name: Commit y push resultados procesados
        env:
          CI_COMMIT_MESSAGE: "Resultados procesados con Spark"
          CI_COMMIT_AUTHOR: "JessicaGarcia1"
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "garsiljes@gmail.com" # Configura el nombre y el correo
          git add . # Agrega todos los cambios realizados
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" # Usa el mensaje del commit
          git push
