name: spark
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]

jobs:
  spark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Revisa el código
      - run: |
          python -m pip install --upgrade pip
          pip install -r streamlit/requirements.txt # Instala dependencias
      - run: |
          python streamlit/procesamiento_spark.py # Ejecuta el script de Spark
      - name: Subir resultados procesados
        run: |
          git config --global user.name "JessicaGarcia1"
          git config --global user.email "garsiljes@gmail.com" # Configura el nombre y el correo
          git add .
          git commit -m "Resultados procesados con Spark"
          git push origin main
